// On exporte par défaut notre tableau d'objets.
// Mettre ce tableau dns un fichier spécifié permet d'alléger le
// fichier qui utilisera ce tableau

export default [
  {
    id: 1,
    price: 50,
    size: "10",
    equipments: "Wi-Fi, projecteur",
    url: "#/spaces/1",
    picture: "https://picsum.photos/id/1060/850.webp",
  },
  {
    id: 2,
    price: 40,
    size: "8",
    equipments: "Wi-Fi, tableau blanc",
    url: "#/spaces/2",
    picture: "https://picsum.photos/id/201/850.webp",
  },
  {
    id: 3,
    price: 60,
    size: "12",
    equipments: "Wi-Fi, imprimante",
    url: "#/spaces/3",
    picture: "https://picsum.photos/id/309/850.webp",
  },
  {
    id: 4,
    price: 70,
    size: "15",
    equipments: "Wi-Fi, machine à café",
    url: "#/spaces/4",
    picture: "https://picsum.photos/id/203/850.webp",
  },
  {
    id: 5,
    price: 55,
    size: "9",
    equipments: "Wi-Fi, tableau blanc, imprimante",
    url: "#/spaces/5",
    picture: "https://picsum.photos/id/204/850.webp",
  },
  {
    id: 6,
    price: 45,
    size: "7",
    equipments: "Wi-Fi, projecteur, machine à café",
    url: "#/spaces/6",
    picture: "https://picsum.photos/id/250/850.webp",
  },
  {
    id: 7,
    price: 65,
    size: "11",
    equipments: "Wi-Fi, tableau blanc, imprimante, machine à café",
    url: "#/spaces/7",
    picture: "https://picsum.photos/id/206/850.webp",
  },
  {
    id: 8,
    price: 75,
    size: "16",
    equipments: "Wi-Fi, projecteur, tableau blanc",
    url: "#/spaces/8",
    picture: "https://picsum.photos/id/260/850.webp",
  },
  {
    id: 9,
    price: 58,
    size: "10",
    equipments: "Wi-Fi, machine à café",
    url: "#/spaces/9",
    picture: "https://picsum.photos/id/208/850.webp",
  },
  {
    id: 10,
    price: 42,
    size: "6",
    equipments: "Wi-Fi",
    url: "#/spaces/10",
    picture: "https://picsum.photos/id/209/850.webp",
  },
  {
    id: 11,
    price: 63,
    size: "13",
    equipments: "Wi-Fi, imprimante",
    url: "#/spaces/11",
    picture: "https://picsum.photos/id/210/850.webp",
  },
  {
    id: 12,
    price: 72,
    size: "14",
    equipments: "Wi-Fi, projecteur, tableau blanc, machine à café",
    url: "#/spaces/12",
    picture: "https://picsum.photos/id/211/850.webp",
  },
];
